// Perguntas do quiz da aba "Aprender". "certa" é a posição da resposta correta em "opcoes".
export const PERGUNTAS = [
  { pergunta: 'Quantos quilos tem uma saca de soja?', opcoes: ['50 kg', '60 kg', '15 kg', '100 kg'], certa: 1,
    explicacao: 'A saca de soja, milho, trigo e café tem 60 kg. A de arroz em casca costuma ter 50 kg.' },
  { pergunta: 'O preço do boi gordo é dado em reais por arroba. Quanto pesa uma arroba?', opcoes: ['10 kg', '15 kg', '30 kg', '60 kg'], certa: 1,
    explicacao: 'Uma arroba são 15 kg. Um boi de 18 arrobas tem 270 kg de carcaça.' },
  { pergunta: 'O que é fazer hedge?', opcoes: ['Guardar a produção esperando o preço subir', 'Travar um preço na bolsa para se proteger da queda', 'Vender a produção fiado', 'Comprar terra em outro estado'], certa: 1,
    explicacao: 'Hedge é proteção: o produtor trava hoje o preço de venda no mercado futuro e deixa de depender do preço do dia da colheita.' },
  { pergunta: 'A soja em Chicago é cotada por bushel. Um bushel de soja tem cerca de:', opcoes: ['27,2 kg', '60 kg', '15 kg', '1 tonelada'], certa: 0,
    explicacao: 'O bushel de soja e de trigo tem 27,2 kg; o de milho, 25,4 kg. Uma saca de 60 kg tem pouco mais de 2 bushels de soja.' },
  { pergunta: 'Chicago ficou parado, mas o dólar subiu. O que tende a acontecer com o preço da soja em reais?', opcoes: ['Cai', 'Não muda', 'Sobe', 'Vai a zero'], certa: 2,
    explicacao: 'A soja é negociada em dólar. Com o dólar mais caro, cada saca vale mais reais, mesmo sem mudança em Chicago.' },
  { pergunta: 'O que é a taxa Selic?', opcoes: ['O imposto sobre a exportação de grãos', 'A taxa básica de juros do Brasil, definida pelo Banco Central', 'O preço mínimo do milho', 'A inflação do mês'], certa: 1,
    explicacao: 'A Selic é a taxa básica de juros, decidida pelo Copom, do Banco Central. Ela influencia os juros do crédito e o câmbio.' },
  { pergunta: 'O que o IPCA mede?', opcoes: ['A produção de grãos do país', 'A inflação oficial: quanto os preços subiram para o consumidor', 'O valor do dólar', 'A chuva do mês'], certa: 1,
    explicacao: 'O IPCA, calculado pelo IBGE, é a inflação oficial do Brasil.' },
  { pergunta: 'O que é uma commodity?', opcoes: ['Um produto padronizado negociado em bolsa, como soja e milho', 'Uma marca de trator', 'Um tipo de adubo', 'Um imposto rural'], certa: 0,
    explicacao: 'Commodities são produtos primários padronizados: a soja de um produtor vale o mesmo que a de outro com a mesma qualidade.' },
  { pergunta: 'Em um contrato futuro, o que é o vencimento?', opcoes: ['O dia em que a lavoura é plantada', 'O mês em que o contrato termina', 'A data de pagamento do adubo', 'A validade da semente'], certa: 1,
    explicacao: 'Cada contrato futuro termina em um mês. "Soja novembro" é a soja para entrega em novembro, e cada mês tem o seu preço.' },
  { pergunta: 'Onde se forma o preço de referência mundial da soja?', opcoes: ['Na Bolsa de Chicago', 'Na B3, em São Paulo', 'Na Bolsa de Londres', 'No porto de Paranaguá'], certa: 0,
    explicacao: 'A Bolsa de Chicago (CBOT) é a referência mundial para soja, milho e trigo.' },
  { pergunta: 'O que é a "base" no mercado de grãos?', opcoes: ['A diferença entre o preço da sua região e o preço da bolsa', 'O custo do frete', 'A parte de baixo do silo', 'O preço mínimo do governo'], certa: 0,
    explicacao: 'Base é a diferença entre o preço físico da região e o preço futuro. Ela reflete frete, oferta local e prêmio do porto.' },
  { pergunta: 'Um mercado com muita volatilidade é um mercado em que os preços:', opcoes: ['Nunca mudam', 'Só sobem', 'Oscilam muito', 'São tabelados'], certa: 2,
    explicacao: 'Volatilidade é o tamanho da oscilação dos preços. O café arábica é um exemplo de mercado muito volátil.' },
  { pergunta: 'No Paraná, quem levanta todo dia o preço pago ao produtor em cada região?', opcoes: ['A Bolsa de Chicago', 'O DERAL, da Secretaria da Agricultura do estado', 'O Banco Central', 'A Receita Federal'], certa: 1,
    explicacao: 'O DERAL (Departamento de Economia Rural) publica a cotação diária de compra pelos atacadistas paranaenses.' },
  { pergunta: 'Quantos hectares tem um alqueire paulista, o mais usado no Paraná?', opcoes: ['1 hectare', '2,42 hectares', '4,84 hectares', '10 hectares'], certa: 1,
    explicacao: 'O alqueire paulista tem 2,42 hectares (24.200 m²). O alqueire mineiro tem o dobro: 4,84 hectares.' },
];
